<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>TMath</PackageId>
        <Title>TMath</Title>
        <Authors>thiagomvas</Authors>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Description>A C# Math library using Generics to add support for more number types.</Description>
        <PackageProjectUrl>https://github.com/thiagomvas/TMath</PackageProjectUrl>
        <RepositoryUrl>https://github.com/thiagomvas/TMath</RepositoryUrl>
        <PackageTags>math, generics, csharp, numerical</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Version>1.3.1</Version>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TMath.Abstractions\TMath.Abstractions.csproj" />
    </ItemGroup>


    <PropertyGroup>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>


</Project>
