<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>TMath.Abstractions</PackageId>
        <Title>TMath.Abstractions</Title>
        <Authors>thiagomvas</Authors>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Description>Abstractions for TMath, a generics math library.</Description>
        <PackageProjectUrl>https://github.com/thiagomvas/TMath.Abstractions</PackageProjectUrl>
        <RepositoryUrl>https://github.com/thiagomvas/TMath.Abstractions</RepositoryUrl>
        <PackageTags>math, generics, csharp, numerical, abstractions</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Version>2.0.0-alpha</Version>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
